# Emscripten/WebGL 2 additions. Native project-generator settings remain valid.
PROJECT_LDFLAGS += --bind
PROJECT_LDFLAGS += -sMODULARIZE=1
PROJECT_LDFLAGS += -sEXPORT_ES6=1
PROJECT_LDFLAGS += -sEXPORT_NAME=createOfxOGrafModule
PROJECT_LDFLAGS += -sALLOW_MEMORY_GROWTH=1
PROJECT_LDFLAGS += -sMIN_WEBGL_VERSION=2
PROJECT_LDFLAGS += -sMAX_WEBGL_VERSION=2
PROJECT_LDFLAGS += -sENVIRONMENT=web
